#The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#Let us list the factors of the first seven triangle numbers:
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
#10: 1,2,5,10
#15: 1,3,5,15
#21: 1,3,7,21
#28: 1,2,4,7,14,28
#We can see that 28 is the first triangle number to have over five divisors.
#What is the value of the first triangle number to have over five hundred divisors?

divCnt = 500
upto = 1
currentDivCnt = 0
divCntNum = 0

while currentDivCnt < divCnt:
    currentDivCnt = 0
    upto += 1
    nums = sum(range(1,upto+1))
    #find divisors
    #print([i for i in range(1,upto+1)],',')
    currentDivCnt = len([x for x in range(1,nums+1) if nums % x == 0])
    print('sum = ' + str(nums) + ' div count = ' + str(currentDivCnt))
    divCntNum = nums

print(upto)
print(divCntNum)
